// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactApp1.Server.Models;

public partial class ActivitiesModel
{
    public int ModelId { get; set; }

    public string ModelName { get; set; }

    public virtual ICollection<ModelJoint> ModelJoints { get; set; } = new List<ModelJoint>();
}