// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactApp1.Server.Models;

public partial class ClassJoint
{
    public int ClassJointId { get; set; }

    public int ActivityId { get; set; }

    public int ClassId { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual ClassName Class { get; set; }
}