// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactApp1.Server.Models;

public partial class ClassName
{
    public int ClassId { get; set; }

    public string ClassName1 { get; set; }

    public virtual ICollection<ClassJoint> ClassJoints { get; set; } = new List<ClassJoint>();
}