// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactApp1.Server.Models;

public partial class Hotel
{
    public int HotelId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public byte[] HotelPhoto { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();
}